### ISSUE TITLE
Does it have integration with aiohttp using gunicorn?

### ISSUE THREAD

**Issue by jeicoo** [Skyscanner/aiotask-context#25]
I have an `aiohttp` web application which are deployed under `gunicorn`. So I am using `gunicorn` to start my application. I want to have a location in which I can store request ID. In that way, I can now use log without passing the request ID every time.

From what I understand, the `loop`'s task factory should be replaced first with the factory that `aiotask-context` provided. After that, I can now store request ID and use it in `logging.Filter`. 

It seems that I cannot set the task factory of the loop since creating the event loop is inside of the `aiohttp.GunicornWebWorker`. Is it possible that I can use `aiotask-context` without dropping the use of `gunicorn`?

**Comment by argaen** [comment]
You won't be losing whatever loop you are using. With aiotask you just set the task factory, but then `asyncio.get_event_loop()` will return whatever loop you've configured. The only difference is that the task object is slightly customized to contain a `context` attribute where you can store things
